language: php

php: 
  - 5.4
  - 5.5
  - 5.6

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

notifications:
  email:
    - intrip@gmail.com
    - falanga.fra@gmail.com
    - alessandro231@gmail.com

script: phpunit